# Generated by Django 6.0.4 on 2026-05-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParishProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa Parafii')),
                ('description', models.TextField(blank=True, verbose_name='Opis (Rich Text)')),
                ('address', models.TextField(verbose_name='Adres')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('primary_color', models.CharField(default='#D4AF37', help_text='HEX gold color', max_length=7)),
                ('secondary_color', models.CharField(default='#1F1F1F', help_text='HEX secondary color', max_length=7)),
                ('background_color', models.CharField(default='#121212', help_text='HEX dark background', max_length=7)),
                ('logo_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Profil Parafii',
                'verbose_name_plural': 'Profile Parafii',
            },
        ),
    ]
